-- public.app_settings definition

-- Drop table

-- DROP TABLE public.app_settings;

CREATE TABLE public.app_settings (
	setting_key varchar(50) NULL,
	setting_value varchar(100) NULL,
	description text NULL,
	updated_at timestamp NULL
);


-- public.audit_logs definition

-- Drop table

-- DROP TABLE public.audit_logs;

CREATE TABLE public.audit_logs (
	log_id bigserial NOT NULL,
	actor_user_id int4 NULL,
	"action" varchar(50) NULL,
	target_table varchar(50) NULL,
	target_record_id varchar(50) NULL,
	ip_address varchar(50) NULL,
	keterangan_detail text NULL,
	created_at timestamp NULL
);


-- public.data_pegawai definition

-- Drop table

-- DROP TABLE public.data_pegawai;

CREATE TABLE public.data_pegawai (
	id int4 NOT NULL,
	pin varchar(50) NULL,
	nip varchar(50) NULL,
	nama_lengkap varchar(100) NULL,
	CONSTRAINT data_pegawai_nip_key UNIQUE (nip)
);


-- public.devices definition

-- Drop table

-- DROP TABLE public.devices;

CREATE TABLE public.devices (
	sn varchar(50) NULL,
	"name" varchar(100) NULL,
	device_name varchar(100) NULL,
	mac_address varchar(50) NULL,
	ip_address varchar(50) NULL,
	fw_version varchar(50) NULL,
	platform varchar(50) NULL,
	last_activity timestamp NULL,
	timezone varchar(50) NULL,
	verified bool NULL,
	initial_sync_completed int4 NULL,
	user_count int4 NULL,
	transaction_count int4 NULL,
	opd_id int4 NULL,
	registered_by int4 NULL,
	anti_spoofing_enabled bool NOT NULL
);


-- public.hari_libur_custom definition

-- Drop table

-- DROP TABLE public.hari_libur_custom;

CREATE TABLE public.hari_libur_custom (
	id int4 NOT NULL,
	tanggal date NOT NULL,
	keterangan varchar(200) NULL,
	created_at timestamp NULL
);


-- public.master_opd definition

-- Drop table

-- DROP TABLE public.master_opd;

CREATE TABLE public.master_opd (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nama_opd varchar(100) NULL,
	kode_opd varchar(50) NULL,
	alamat_opd text NULL,
	created_at timestamp NULL,
	CONSTRAINT master_opd_pkey PRIMARY KEY (id)
);


-- public.sn_mesin definition

-- Drop table

-- DROP TABLE public.sn_mesin;

CREATE TABLE public.sn_mesin (
	sn varchar(50) NULL,
	opd_id int4 NOT NULL,
	nama_lokasi varchar(100) NULL
);


-- public.user_admin definition

-- Drop table

-- DROP TABLE public.user_admin;

CREATE TABLE public.user_admin (
	id int4 NOT NULL,
	user_id int4 NOT NULL,
	bound_device_sn varchar(50) NULL,
	created_at timestamp NULL
);


-- public.user_akses_opd definition

-- Drop table

-- DROP TABLE public.user_akses_opd;

CREATE TABLE public.user_akses_opd (
	id int4 NOT NULL,
	user_nip varchar(50) NULL,
	opd_id int4 NOT NULL,
	approval_status varchar(20) NULL,
	created_at timestamp NULL
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	user_id int4 NOT NULL,
	user_nip varchar(50) NULL,
	user_pin varchar(50) NULL,
	nama_lengkap varchar(100) NULL,
	opd_id int4 NULL,
	"role" varchar(11) NULL,
	password_hash varchar(255) NULL,
	is_face_registered bool NULL,
	approval_status varchar(20) NULL,
	created_at timestamp NULL,
	username varchar(100) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (user_id)
);


-- public.jadwal_kegiatan definition

-- Drop table

-- DROP TABLE public.jadwal_kegiatan;

CREATE TABLE public.jadwal_kegiatan (
	id serial4 NOT NULL,
	nama_kegiatan varchar(150) NOT NULL,
	keterangan text NULL,
	alamat_lokasi text NULL,
	latitude_target float8 NOT NULL,
	longitude_target float8 NOT NULL,
	radius_toleransi int4 DEFAULT 100 NOT NULL,
	tanggal_mulai date NOT NULL,
	tanggal_selesai date NOT NULL,
	opd_id int4 NULL,
	created_by int4 NOT NULL,
	created_at timestamp DEFAULT (now() AT TIME ZONE 'Asia/Jakarta'::text) NULL,
	is_global bool DEFAULT false NULL,
	jam_mulai time NULL,
	jam_selesai time NULL,
	CONSTRAINT jadwal_kegiatan_pkey PRIMARY KEY (id),
	CONSTRAINT jadwal_kegiatan_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id) ON DELETE RESTRICT,
	CONSTRAINT jadwal_kegiatan_opd_id_fkey FOREIGN KEY (opd_id) REFERENCES public.master_opd(id) ON DELETE RESTRICT
);


-- public.peserta_kegiatan definition

-- Drop table

-- DROP TABLE public.peserta_kegiatan;

CREATE TABLE public.peserta_kegiatan (
	id serial4 NOT NULL,
	kegiatan_id int4 NOT NULL,
	nip varchar(50) NOT NULL,
	CONSTRAINT peserta_kegiatan_pkey PRIMARY KEY (id),
	CONSTRAINT uq_kegiatan_nip UNIQUE (kegiatan_id, nip),
	CONSTRAINT peserta_kegiatan_kegiatan_id_fkey FOREIGN KEY (kegiatan_id) REFERENCES public.jadwal_kegiatan(id) ON DELETE CASCADE,
	CONSTRAINT peserta_kegiatan_nip_fkey FOREIGN KEY (nip) REFERENCES public.data_pegawai(nip) ON DELETE CASCADE
);


-- public.presensi definition

-- Drop table

-- DROP TABLE public.presensi;

CREATE TABLE public.presensi (
	log_id bigserial NOT NULL,
	device_sn varchar(50) NULL,
	user_pin varchar(50) NULL,
	waktu_presensi timestamp NOT NULL,
	tipe_absen varchar(3) NULL,
	status_kehadiran varchar(11) NULL,
	keterlambatan_menit int4 NULL,
	kegiatan_id int4 NULL,
	latitude_scan float8 NULL,
	longitude_scan float8 NULL,
	CONSTRAINT presensi_kegiatan_id_fkey FOREIGN KEY (kegiatan_id) REFERENCES public.jadwal_kegiatan(id) ON DELETE SET NULL
);